### ISSUE TITLE
DB dump

### ISSUE THREAD

**Issue by giograno** [idflakies/iDFlakies#24]
Hello, thanks for the nice work done by sharing this replication package.
I was wondering whether would it be possible to share a dump of the database with the results described in the paper.
Thank you very much in advance.

**Comment by winglam** [comment]
Hello Giovanni,

You can find a dump of the SQL database we used for the paper [here](https://drive.google.com/file/d/1hIDlrra1bm8QTTRD7z-veCtTQi743Z90).

The format of the database is as described [here](https://github.com/idflakies/iDFlakies/tree/master/scripts#database-format).

Thanks for your interest in the work. If you have any additional problems, please do let us know.
