### ISSUE TITLE
Absolute paths for optional scripts passed to run_experiment.sh not correctly handled

### ISSUE THREAD

**Issue by s-winter** [idflakies/iDFlakies#4]
When invoking run_experiment.sh with an optional script parameter ($4) and the parameter refers to an absolute path within the docker container, the path is treated like a relative path and appended to "/home/$SCRIPT_USERNAME/$TOOL_REPO/scripts/docker/". The reason is that the test for absolute paths in run_experiment.sh quotes the regex, which is then interpreted as a literal string. Moreover, the regex uses the end instead of the start anchor.

**Comment by august782** [comment]
Issue resolved.
